spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miruni_test
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

perplexity:
  api-key: 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
  api-url: https://api.perplexity.ai/chat/completions