spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miruni_test
    username: root
    password: Rlaehgns10!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
      
  redis:
    host: localhost
    port: 6379
    timeout: 2000
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
